version: 2

models:
  - name: dim_zones
    description: A dimension table containing details about the NYC taxi zones.
    columns:
      - name: locationid
        description: The unique identifier for the taxi zone.
        tests:
          - unique
          - not_null
      - name: borough
        description: The NYC borough where the zone is located.
      - name: zone
        description: The name of the taxi zone.
      - name: service_zone
        description: The service zone category (e.g., Green, Yellow, EWR).

  - name: fact_trips
    description: A fact table containing all NYC taxi trips, unioning green and yellow taxi data. This is an incremental model.
    columns:
      - name: tripid
        description: The unique identifier for each trip.
        tests:
          - unique
          - not_null
      - name: vendorid
        description: A code indicating the TPEP provider.
      - name: service_type
        description: The type of taxi service (Green or Yellow).
      - name: pickup_locationid
        description: The taxi zone ID where the trip began.
      - name: dropoff_locationid
        description: The taxi zone ID where the trip ended.
      - name: pickup_datetime
        description: The timestamp when the trip began.
      - name: total_amount
        description: The total amount paid for the trip.
      - name: payment_type
        description: A numeric code for the payment method.
      - name: payment_type_description
        description: The description of the payment method.
      - name: airport_fee
        description: Fee for pickups at LaGuardia and JFK airports (Yellow taxis only).
      - name: cbd_congestion_fee
        description: Fee for trips in the central business district.

  - name: dm_monthly_zone_revenue
    description: A data mart table aggregating monthly taxi metrics by pickup zone and service type. This is the primary model for BI and reporting.
    columns:
      - name: pickup_borough
        description: The borough where trips originated.
        tests:
          - not_null
      - name: pickup_zone
        description: The taxi zone where trips originated.
        tests:
          - not_null
      - name: service_type
        description: The type of taxi service (Green or Yellow).
        tests:
          - not_null
      - name: revenue_month
        description: The month for which the metrics are aggregated.
        tests:
          - not_null
      - name: revenue_monthly_fare
        description: Total monthly revenue from the base fare.
      - name: revenue_monthly_extra
        description: Total monthly revenue from extra charges (e.g., rush hour).
      - name: revenue_monthly_mta_tax
        description: Total monthly revenue from MTA tax.
      - name: revenue_monthly_tip_amount
        description: Total monthly revenue from tips.
      - name: revenue_monthly_tolls_amount
        description: Total monthly revenue from tolls.
      - name: revenue_monthly_ehail_fee
        description: Total monthly revenue from e-hail fees.
      - name: revenue_monthly_improvement_surcharge
        description: Total monthly revenue from improvement surcharges.
      - name: revenue_monthly_congestion_surcharge
        description: Total monthly revenue from standard congestion surcharges.
      - name: revenue_monthly_cbd_congestion_fee
        description: Total monthly revenue from the Central Business District congestion fee.
      - name: revenue_monthly_airport_fee
        description: Total monthly revenue from airport fees.
      - name: revenue_monthly_total_amount
        description: The total gross monthly revenue, summing all components.
      - name: total_monthly_trips
        description: The total number of trips for the month in that zone and service type.
      - name: avg_monthly_passenger_count
        description: The average number of passengers per trip for the month.
      - name: avg_monthly_trip_distance
        description: The average trip distance in miles for the month.
